In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2019-tweets/2019_tweets.csv/2019_tweets.csv
/kaggle/input/2019-tweets/2019_detailed_tweets.csv/2019_detailed_tweets.csv
/kaggle/input/2020-tweets/2020_detailed_tweets.csv/2020_detailed_tweets.csv
/kaggle/input/2020-tweets/2020_tweets.csv/2020_tweets.csv
/kaggle/input/rep-names/rep_names.csv

In [2]:
reps = pd.read_csv("../input/rep-names/rep_names.csv")

In [3]:
tweets_19 = pd.read_csv("../input/2019-tweets/2019_detailed_tweets.csv/2019_detailed_tweets.csv", engine='python')
tweets_20 = pd.read_csv("../input/2020-tweets/2020_detailed_tweets.csv/2020_detailed_tweets.csv", engine='python')

In [4]:
tweets_19.head()

,tweet,id,conversation_id,party
0,I am humbled to have been named an honorary Tu...,1218644793154244611,1218644793154244611,D
1,Thanks to everyone who stopped by my Mobile Mc...,1217904241592938520,1217904241592938520,D
2,Middle and high school students still have thr...,1217850247562637312,1217850247562637312,D
3,Happy to stand w. @AARP &amp; older Americans ...,1217613766151561216,1217613766151561216,D
4,REMINDER: Tomorrow morning my office is hostin...,1217599344398032898,1217599344398032898,D

In [5]:
tweets_20.head()

,tweet,id,conversation_id,party
0,Today I celebrate Dr. King's legacy as a stone...,1351180525403328513,1351180525403328513,D
1,Neither did I,1350242666093621254,1350242666093621254,D
2,I am so proud to co-sponsor the resolution to ...,1350159210949046278,1350159210949046278,D
3,What this announcement makes clear is that the...,1350153859746983939,1350153859746983939,D
4,A big congratulations to @DrCameronWebb on his...,1350098453016285186,1350098453016285186,D

In [6]:
tweets_combined = pd.concat([tweets_20, tweets_19])
len(tweets_combined)

1831828

In [7]:
tweets_combined = tweets_combined.drop_duplicates()
len(tweets_combined)

1824331

In [8]:
tweets_combined = tweets_combined.loc[tweets_combined['party'] != "party"]
len(tweets_combined)

1824330

In [9]:
counts = tweets_combined.party.value_counts()
counts

D    1204034
R     620278
Name: party, dtype: int64

In [10]:
selected_dem = tweets_combined.query('party == "D"').sample(counts['R'])

In [32]:
balanced_set = pd.concat([tweets_combined.query('party == "R"'), selected_dem], ignore_index=True)

In [35]:
train = balanced_set.sample(frac = 0.6)
len(train)

744334

In [37]:
non_train = balanced_set.drop(train.index)
len(non_train)

496222

In [38]:
test = non_train.sample(frac = 0.5)
len(test)

248111

In [39]:
val = non_train.drop(test.index)
len(val)

248111

In [ ]:
train.to_csv (r'./train_set.csv', index = False, header=True)
val.to_csv (r'./val_set.csv', index = False, header=True)
test.to_csv (r'./test_set.csv', index = False, header=True)